/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cristiandorado' at '12/11/16 16:02' with Gradle 3.1
 *
 * @author cristiandorado, @date 12/11/16 16:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
